export ASPECT_PROJECT_DIR="/mnt/lochy0/ASPECT_DATA/"
export TwoDSubduction_DIR="/mnt/lochy0/ASPECT_DATA/TwoDSubduction"
export ThDSubduction_DIR="/mnt/lochy0/ASPECT_DATA/ThDSubduction"
export LatentHeatBK_DIR="/mnt/lochy0/ASPECT_DATA/LatentHeatBK"
export LunarModel_DIR="$/mnt/lochy0/ASPECT_DATA/LunarModel"
export TwoDSubduction_ucd_DIR="/home/lochy/ASPECT_PROJECT/TwoDSubduction"