export ASPECT_PROJECT_DIR="$HOME/ASPECT_PROJECT"
export TwoDSubduction_DIR="$HOME/ASPECT_PROJECT/TwoDSubduction"
export ThDSubduction_DIR="$HOME/ASPECT_PROJECT/ThDSubduction"
export LatentHeatBK_DIR="$HOME/ASPECT_PROJECT/LatentHeatBK"
export LunarModel_DIR="$HOME/ASPECT_PROJECT/LunarModel"
export TwoDSubduction_ucd_DIR="/home/lochy/ASPECT_PROJECT/TwoDSubduction"