export ASPECT_PROJECT_DIR="$HOME/ASPECT_PROJECT"
export ASPECT_SOURCE_DIR="/group/billengrp/lochy/softwares/aspect"
export ASPECT_LAB_DIR="$HOME/ASPECT_PROJECT/aspectLib"
export TwoDSubduction_DIR="/group/billengrp-mpi-io/lochy/TwoDSubduction"
export ThDSubduction_DIR="/group/billengrp-mpi-io/lochy/ThDSubduction"
export LatentHeatBK_DIR="/group/billengrp-mpi-io/lochy/LatentHeatBK"
export EntropySub_DIR="/group/billengrp-mpi-io/lochy/EntropySub"
export SQUEUE="/share/apps/slurm-19.05.3/18.04/bin/squeue"
export SCANCEL="/share/apps/slurm-19.05.3/18.04/bin/scancel"
alias all_case_info="Lib_parse_case all_case_info"
alias all_case_info_in_dir="Lib_parse_case case_info_in_dir ."
alias check_restart_dir=" Lib_parse_case  check_time_restart_directory . 59e6 p-billen"
alias check_no_restart_dir=" Lib_parse_case  check_time_restart_directory . 59e6 0"
alias check_restartr=" Lib_parse_case  check_time_restart . 59e6 p-billen"
alias check_no_restartr=" Lib_parse_case  check_time_restart . 59e6 0"
[[ -e "${ASPECT_LAB_DIR}/enable.sh" ]] && source "${ASPECT_LAB_DIR}/enable.sh"
