export ASPECT_PROJECT_DIR="/mnt/lochy0/ASPECT_DATA/"
export TwoDSubduction_DIR="/mnt/lochy0/ASPECT_DATA/TwoDSubduction"
export ThDSubduction_DIR="/mnt/lochy0/ASPECT_DATA/ThDSubduction"
export LatentHeatBK_DIR="/mnt/lochy0/ASPECT_DATA/LatentHeatBK"
export EntropySub_DIR="/mnt/lochy0/ASPECT_DATA/EntropySubduction"
export LunarModel_DIR="$/mnt/lochy0/ASPECT_DATA/LunarModel"
export TwoDSubduction_ucd_DIR="/home/lochy/ASPECT_PROJECT/TwoDSubduction"
alias Lib_TwoDSubduction0_run_docker="xhost + && docker run --user root --rm -ti --net=host --ipc=host -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix --env="QT_X11_NO_MITSHM=1" -it visitdev:3.1.3-ubuntu16-work"
