export ASPECT_PROJECT_DIR="$HOME/ASPECT_PROJECT"
export ASPECT_SOURCE_DIR="/group/billengrp/lochy/softwares/aspect"
export ASPECT_LAB_DIR="$HOME/ASPECT_PROJECT/aspectLib"
export TwoDSubduction_DIR="/group/billengrp-mpi-io/lochy/TwoDSubduction"
export LatentHeatBK_DIR="/group/billengrp-mpi-io/lochy/LatentHeatBK"
export SQUEUE="/share/apps/slurm-19.05.3/18.04/bin/squeue"
export SCANCEL="/share/apps/slurm-19.05.3/18.04/bin/scancel"
alias submit_case="slurm.sh -l /home/lochy/ASPECT_PROJECT/aspectLib/.output/job.log -lt ./output/machine_time"
export LearnAspect_DIR="/home/lochy/ASPECT_PROJECT/LearnAspect"
[[ -e "${ASPECT_LAB_DIR}/enable.sh" ]] && source "${ASPECT_LAB_DIR}/enable.sh"
